### ISSUE TITLE
How to run `hummingbird_ws` on px4 gazebo?

### ISSUE THREAD

**Issue by xdwgood** [utiasSTARS/hummingbird#17]
Hello everyone!

I use `hummingbird_sitl_gazebo` file  replace to `sitl_gazebo` file.
then I try run `make px4_sitl gazebo_hummingbird_fixed`
I got error:
```
ninja: error: unknown target 'gazebo_hummingbird_fixed'
Makefile:200: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1
```

Any guidance is welcome, thank you very much

**Comment by Vuwij** [comment]
Hello. I'm the new maintainer for this repository. I'm planning to clean it up and fix a lot of things but I haven't started yet. May I ask your background and who you are?

**Comment by xdwgood** [comment]
Hi @Vuwij 
I am a px4 flight control developer

**Comment by xdwgood** [comment]
@Vuwij  any help?  thanks

**Comment by Vuwij** [comment]
Hi I'm still cleaning up the repository. The simulation is not up to date with the design at all. I'll make a large push to master and then I can give you some guidance. Where are you located btw

**Comment by xdwgood** [comment]
@Vuwij  that will be great!
I am in china
